# Nguyễn Thành Trí - MSSV: 6451071079
## Bài 2 (Trang 28-29) - Câu 1: Nhập dữ liệu Bank Marketing và thống kê thông tin cơ bản

### Đề bài:
Để thực hiện chiến dịch marketing cho chương trình gửi tiền có kì hạn, một ngân hàng dựa trên bộ dữ liệu người dùng để tìm hiểu khả năng người dùng sẽ đăng kí chương trình gửi tiền có kì hạn hay không.
Thực hiện:
- Đọc dữ liệu từ file `bank.csv` (hoặc `bank-full.csv`).
- Hiển thị các dòng đầu tiên (`head()`), cấu trúc và kiểu dữ liệu (`info()`).
- Thống kê chỉ số của các thuộc tính định lượng (`describe()`).

In [1]:
# Nguyễn Thành Trí - 6451071079
# Bài 2 (Trang 28-29) - Câu 1: Nhập dữ liệu và kiểm tra cấu trúc

import os
import pandas as pd
import numpy as np

print("Họ tên: Nguyễn Thành Trí - MSSV: 6451071079")

# Hàm lấy đường dẫn an toàn
def get_data_path(rel_path):
    candidates = [
        rel_path,
        os.path.join("..", rel_path),
        os.path.join("..", "..", rel_path),
        os.path.join("datasets", os.path.basename(rel_path)),
        os.path.join("..", "datasets", os.path.basename(rel_path)),
        os.path.join("..", "..", "datasets", os.path.basename(rel_path)),
        os.path.join("..", "..", "datasets", "Bank", os.path.basename(rel_path)),
        os.path.join("datasets", "Bank", os.path.basename(rel_path))
    ]
    for p in candidates:
        if os.path.exists(p):
            return p
    raise FileNotFoundError(f"Không tìm thấy file dữ liệu: {rel_path}")

file_path = get_data_path("bank.csv")
print("Đường dẫn file dữ liệu:", file_path)

# File bank.csv sử dụng dấu chấm phẩy (;) làm dấu phân cách
df = pd.read_csv(file_path, sep=';')

print(f"Kích thước tập dữ liệu: {df.shape[0]} dòng, {df.shape[1]} cột.")
print()
print("5 dòng đầu tiên của tập dữ liệu:")
display(df.head())

Họ tên: Nguyễn Thành Trí - MSSV: 6451071079
Đường dẫn file dữ liệu: ../../datasets/Bank/bank.csv
Kích thước tập dữ liệu: 4521 dòng, 17 cột.

5 dòng đầu tiên của tập dữ liệu:

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [2]:
# Nguyễn Thành Trí - 6451071079
# Bài 2 (Trang 28-29) - Câu 1: Cấu trúc dữ liệu và thống kê mô tả

print("Họ tên: Nguyễn Thành Trí - MSSV: 6451071079")

print("Thông tin cấu trúc tập dữ liệu (df.info()):")
df.info()

print()
print("Thống kê mô tả các thuộc tính định lượng (df.describe()):")
display(df.describe())

Họ tên: Nguyễn Thành Trí - MSSV: 6451071079
Thông tin cấu trúc tập dữ liệu (df.info()):
<class 'pandas.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   str
 2   marital    4521 non-null   str
 3   education  4521 non-null   str
 4   default    4521 non-null   str
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   str
 7   loan       4521 non-null   str
 8   contact    4521 non-null   str
 9   day        4521 non-null   int64
 10  month      4521 non-null   str
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   str
 16  y          4521 non-null   str
dtypes: int64(7), str(10)
memory usage: 600.6 KB

Thống kê mô tả các thuộc tính định lượng (df.describe()):

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

### Nhận xét & Đánh giá (Câu 1):
1. **Quy mô tập dữ liệu**: Tập dữ liệu `bank.csv` gồm **4,521** bản ghi và **17** thuộc tính (16 thuộc tính đầu vào và 1 thuộc tính mục tiêu `y` biểu diễn khách hàng có đăng ký gửi tiết kiệm có kỳ hạn hay không).
2. **Các nhóm thuộc tính**:
   - *Thông tin khách hàng*: `age` (độ tuổi), `job` (nghề nghiệp), `marital` (tình trạng hôn nhân), `education` (học vấn), `default` (tín dụng mặc định), `balance` (số dư tài khoản bình quân), `housing` (vay mua nhà), `loan` (vay cá nhân).
   - *Thông tin chiến dịch hiện tại*: `contact` (hình thức liên lạc), `day` (ngày trong tháng), `month` (tháng liên lạc), `duration` (thời lượng cuộc gọi tính bằng giây).
   - *Thông tin chiến dịch trước đó*: `campaign` (số lần liên hệ trong chiến dịch), `pdays` (số ngày kể từ lần liên hệ trước, `-1` là chưa từng liên hệ), `previous` (số lần liên hệ trước đó), `poutcome` (kết quả chiến dịch trước).
   - *Thuộc tính quyết định*: `y` ('yes' / 'no').
3. **Thống kê sơ bộ**:
   - Độ tuổi trung bình của khách hàng là **41.17 tuổi** (từ 19 đến 87 tuổi).
   - Số dư tài khoản bình quân (`balance`) là **1,422.66 Euro**, có độ lệch chuẩn rất lớn (**3,009.64 Euro**) phản ánh sự phân hóa giàu nghèo cao.
   - Thời lượng cuộc gọi trung bình (`duration`) là **263.96 giây** (~4.4 phút), từ 4 giây đến 3,025 giây.